import '../profile_onboarding/select_interest_screen.dart';

List<Interest> userInterests = [
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
  Interest(title: "Travel"),
  Interest(title: "Food"),
  Interest(title: "Art"),
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
  Interest(title: "Travel"),
  Interest(title: "Food"),
  Interest(title: "Art"),
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
  Interest(title: "Travel"),
  Interest(title: "Food"),
  Interest(title: "Art"),
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
  Interest(title: "Travel"),
  Interest(title: "Food"),
  Interest(title: "Art"),
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
  Interest(title: "Travel"),
  Interest(title: "Food"),
  Interest(title: "Art"),
  Interest(title: "Music"),
  Interest(title: "Sports"),
  Interest(title: "Movies"),
];
